# Generated by Django 5.2.8 on 2025-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_description_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('BR', 'Berat'), ('BU', 'Bulqize'), ('DL', 'Delvine'), ('DV', 'Devoll'), ('DR', 'Durres'), ('EL', 'Elbasan'), ('FR', 'Fier'), ('GJ', 'Gjirokaster'), ('GR', 'Gramsh'), ('HA', 'Has'), ('KA', 'Kavaje'), ('KB', 'Kurbin'), ('KC', 'Kucove'), ('KO', 'Korce'), ('KR', 'Kruje'), ('KU', 'Kukes'), ('LB', 'Librazhd'), ('LE', 'Lezhe'), ('LU', 'Lushnje'), ('MM', 'Mallakaster'), ('MR', 'Mirdite'), ('MT', 'Mat'), ('PQ', 'Peqin'), ('PR', 'Permet'), ('PG', 'Pogradec'), ('PU', 'Puke'), ('SH', 'Shkoder'), ('SK', 'Skrapar'), ('SR', 'Sarande'), ('TE', 'Tepelene'), ('Tirane', 'Tirane'), ('TP', 'Tropoje'), ('VL', 'Vlore')], max_length=100),
        ),
    ]
