# Generated by Django 5.2.8 on 2025-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Berat', 'Berat'), ('Bulqize', 'Bulqize'), ('Delvine', 'Delvine'), ('Devoll', 'Devoll'), ('Durres', 'Durres'), ('Elbasan', 'Elbasan'), ('Fier', 'Fier'), ('Gjirokaster', 'Gjirokaster'), ('Gramsh', 'Gramsh'), ('Has', 'Has'), ('Kavaje', 'Kavaje'), ('Kurbin', 'Kurbin'), ('Kucove', 'Kucove'), ('Korce', 'Korce'), ('Kruje', 'Kruje'), ('Kukes', 'Kukes'), ('Librazhd', 'Librazhd'), ('Lezhe', 'Lezhe'), ('Lushnje', 'Lushnje'), ('Mallakaster', 'Mallakaster'), ('Mirdite', 'Mirdite'), ('Mat', 'Mat'), ('Peqin', 'Peqin'), ('Permet', 'Permet'), ('Pogradec', 'Pogradec'), ('Puke', 'Puke'), ('Shkoder', 'Shkoder'), ('Skrapar', 'Skrapar'), ('Sarande', 'Sarande'), ('Tepelene', 'Tepelene'), ('Tirane', 'Tirane'), ('Tropoje', 'Tropoje'), ('Vlore', 'Vlore')], max_length=100),
        ),
    ]
