# Generated by Django 5.2.8 on 2025-12-02 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_history_report',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
